import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export const useRecordStore = create(
  persist(
    (set, get) => ({
  records: [],
  selectedRecord: null,
  availableFields: [], // Track available fields from CSV
  
  // Perplexity AI Configuration
  perplexityConfig: {
    apiKey: '',
    prompt: '',
    useDeepResearch: false,
    selectedModel: 'sonar',
    customProperties: []
  },
  
  setSelectedRecord: (record) => set({ selectedRecord: record }),
  
  // Perplexity config actions
  updatePerplexityConfig: (updates) => set(state => ({
    perplexityConfig: { ...state.perplexityConfig, ...updates }
  })),
  
  setPerplexityApiKey: (apiKey) => set(state => ({
    perplexityConfig: { ...state.perplexityConfig, apiKey }
  })),
  
  addRecords: (newRecords) => {
    const currentRecords = get().records;
    const recordsWithIds = newRecords.map(record => ({
      ...record,
      id: record.id || `record_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      augmentationResults: null,
      lastAugmented: null,
      customProperties: {} // Store custom properties generated by AI
    }));
    
    // Extract available fields from the new records
    const newFields = newRecords.length > 0 ? Object.keys(newRecords[0]) : [];
    const currentFields = get().availableFields;
    const allFields = [...new Set([...currentFields, ...newFields])];
    
    set({ 
      records: [...currentRecords, ...recordsWithIds],
      availableFields: allFields
    });
  },
  
  replaceAllRecords: (newRecords) => {
    const recordsWithIds = newRecords.map(record => ({
      ...record,
      id: record.id || `record_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      augmentationResults: null,
      lastAugmented: null,
      customProperties: {} // Store custom properties generated by AI
    }));
    
    // Extract available fields from the new records
    const newFields = newRecords.length > 0 ? Object.keys(newRecords[0]) : [];
    
    set({ 
      records: recordsWithIds,
      availableFields: newFields,
      selectedRecord: null
    });
  },
  
  deleteRecord: (recordId) => {
    const currentRecords = get().records;
    set({ records: currentRecords.filter(record => record.id !== recordId) });
  },
  
  deleteAllRecords: () => set({ records: [], selectedRecord: null, availableFields: [] }),
  
  updateRecordAugmentation: (recordId, augmentationData) => {
    const currentRecords = get().records;
    const updatedRecords = currentRecords.map(record => 
      record.id === recordId 
        ? { 
            ...record, 
            augmentationResults: augmentationData.result,
            lastAugmented: augmentationData.timestamp,
            customProperties: {
              ...record.customProperties,
              ...augmentationData.customProperties
            }
          }
        : record
    );
    set({ records: updatedRecords });
  },
  
  clearRecordAugmentation: (recordId) => {
    const currentRecords = get().records;
    const updatedRecords = currentRecords.map(record => 
      record.id === recordId 
        ? { 
            ...record, 
            augmentationResults: null,
            lastAugmented: null,
            customProperties: {}
          }
        : record
    );
    set({ records: updatedRecords });
  },

  // Add custom properties to available fields when they're generated
  addCustomFields: (customFields) => {
    const currentFields = get().availableFields;
    const newFields = [...new Set([...currentFields, ...customFields])];
    set({ availableFields: newFields });
  },
}),
    {
      name: 'record-collector-storage',
      partialize: (state) => ({
        perplexityConfig: state.perplexityConfig,
        records: state.records,
        availableFields: state.availableFields
      })
    }
  )
); 